app/user_management/__init__.py
from flask import Blueprint

user_management_blueprint = Blueprint('user_management', __name__, template_folder='templates')
from app.user_management import routes,subscription

app/user_management/routes.py
from app import app, db,login
from flask import render_template,redirect,g
from flask import flash, url_for
from flask_login import login_user, logout_user, current_user,login_required
from app.forms import EditProfileForm, LoginForm, RegistrationForm
from app.models import Event, Permission, Program, Stage, User

from urllib import request
from werkzeug.exceptions import abort
from werkzeug.urls import url_parse
from _datetime import datetime
from app.user_management import user_management_blueprint
from sqlalchemy.orm import session
from app.products.forms import SearchForm

@user_management_blueprint.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    # g.locale = str(get_locale())
        
@user_management_blueprint.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


@user_management_blueprint.route('/')
@user_management_blueprint.route('/index')
def index():
   
    return render_template ('user_management/index.html')
   # return 'Welcome home'



    
@user_management_blueprint.route('/specific_program/<program_id>', methods = ['GET','POST'])
@login_required
def specific_program(program_id):
    
    program = Program.query.filter(Program.program_id == program_id).first()
    print (program)
    results = db.session.query(Stage.stage_name,Stage.start,Stage.end,Event.event_description).join(Event).join(Program).\
        filter(Program.program_id == program_id).all()
    
    result_dict = {}    
    result =convert(results,result_dict)

    return render_template('user_management/specific_program.html', result=result,program = program)

def convert(tupl, dic):
    y=()
    x = []
    for name,start,end,event in tupl:
        x.append(name)
        x.append(start)
        x.append(end)
        s=x[-3:]
        y=tuple(s)
        dic.setdefault(y,[]).append(event)
        
        
    return dic


@user_management_blueprint.route('/get_program', methods=['GET','POST'])
@login_required
def get_program():
    programs = Program.query.all()
    return render_template('user_management/programs.html',programs=programs)





@user_management_blueprint.route('/feeds')
def feeds():
    return 'I am feeds'

@user_management_blueprint.route('/vaccines')
def vaccines():
    return 'I am Vaccines'


@user_management_blueprint.route('/market')
def market():
    return 'I am Market'

@user_management_blueprint.route('/housing')
def housing():
    return 'I am Housing'

app/user_management/templates/user_management/index.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap"
		rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="../../../static/css/animate.css">

	<link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
	<link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
	<link rel="stylesheet" href="../../../static/css/magnific-popup.css">


	<link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
	<link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">

	<link rel="stylesheet" href="../../../static/css/flaticon.css">
	<link rel="stylesheet" href="../../../static/css/style.css">
</head>

<body>

	<div class="wrap">
		<div class="container">
			<div class="row">
				<div class="col-md-6 d-flex align-items-center">
					<p class="mb-0 phone pl-md-2">
						
						<a href="#"><span class="fa fa-paper-plane mr-1"></span> chickenrearing@.com</a>
					</p>
				</div>
				<!-- <div class="col-md-6 d-flex justify-content-md-end">
					<div class="social-media">
						<p class="mb-0 d-flex">
							<a href="#" class="d-flex align-items-center justify-content-center"><span
									class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
							<a href="#" class="d-flex align-items-center justify-content-center"><span
									class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>

						</p>
					</div>
				</div> -->
			</div>
		</div>
	</div>
	<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
		<div class="container">
			<a class="navbar-brand" href="{{ url_for('user_management.index') }}"><span
					class="flaticon-pawprint-1 mr-2"></span>Chicken Rearing </a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
				aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="fa fa-bars"></span> Menu
			</button>
			<div class="collapse navbar-collapse" id="ftco-nav">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active"><a href="{{ url_for('user_management.index') }}"
							class="nav-link">Home</a></li>
					<li class="nav-item"><a href="{{ url_for('user_management.get_program')}}" class="nav-link">Managing
							Chicken</a></li>

					<li class="nav-item"> <a href="{{ url_for('products.view_product')}}" class="nav-link">Market Your
							Product</a></li>
					
					{% if current_user.is_anonymous %}
					<li class="nav-item"> <a href="{{ url_for('authentication.login')}}" class="nav-link">Login</a></li>
					{% else %}
					<li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"
							class="nav-link">Profile</a></li>
					<li class="nav-item"> <a href="{{ url_for('authentication.logout')}}" class="nav-link">LogOut</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>
	<!-- END nav -->
	<div class="hero-wrap js-fullheight" style="background-image: url('../../../static/images/5.jpg');"
		data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="container">
			<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
				data-scrollax-parent="true">
				<div class="col-md-11 ftco-animate text-center">
					<h1 class="mb-4">Deep Dive into Chicken Rearing </h1>
					<p><a href="{{ url_for('authentication.login') }}" class="btn btn-primary mr-md-4 py-3 px-4">Learn
							more <span class="ion-ios-arrow-forward"></span></a></p>
				</div>
			</div>
		</div>
	</div>

	<section class="ftco-section bg-light ftco-no-pt ftco-intro">
		<div class="container">
			<div class="row">
				<div class="col-md-4 d-flex align-self-stretch px-4 ftco-animate">
					<div class="d-block services active text-center">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="flaticon-blind"></span>
						</div>
						<div class="media-body">
							<h3 class="heading">Breeds of Chicken</h3>
							<p>Chicken exist in different types </p>
							<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span
									class="fa fa-chevron-right"></span><i class="sr-only">Read more</i></a>
						</div>
					</div>
				</div>
				<div class="col-md-4 d-flex align-self-stretch px-4 ftco-animate">
					<div class="d-block services text-center">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="flaticon-dog-eating"></span>
						</div>
						<div class="media-body">
							<h3 class="heading">Housing</h3>
							<p> Proper housing should be considered when diving into chicken farming</p>
							<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span
									class="fa fa-chevron-right"></span><i class="sr-only">Read more</i></a>
						</div>
					</div>
				</div>
				<div class="col-md-4 d-flex align-self-stretch px-4 ftco-animate">
					<div class="d-block services text-center">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="flaticon-grooming"></span>
						</div>
						<div class="media-body">
							<h3 class="heading">Parasites</h3>
							<p>Parasites can result in stanted growth and reduced outputs</p>
							<a href="#" class="btn-custom d-flex align-items-center justify-content-center"><span
									class="fa fa-chevron-right"></span><i class="sr-only">Read more</i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="ftco-section ftco-no-pt ftco-no-pb">
		<div class="container">
			<div class="row d-flex no-gutters">
					<div class="col-md-5 d-flex">
					<div class="img d-flex align-self-stretch align-items-center justify-content-center justify-content-md-center mb-4 mb-sm-0"
						style="background-image:url(../../../static/ChickImg/k.jpeg);">
					</div>
				</div>
			
				<div class="col-md-7 pl-md-5 py-md-5">
					<div class="heading-section pt-md-5">
						<h2 class="mb-4">Why use this app?</h2>
					</div>
					<div class="row">
						<div class="col-md-6 services-2 w-100 d-flex">
							<div class="icon d-flex align-items-center justify-content-center"><span
									class="flaticon-stethoscope"></span></div>
							<div class="text pl-3">
								<h4>Programs</h4>
								<p>It provides a structured guide on how to rear chicken in terms of programs,stages and
									events</p>

							</div>
						</div>
						<div class="col-md-6 services-2 w-100 d-flex">
							<div class="icon d-flex align-items-center justify-content-center"><span
									class="flaticon-customer-service"></span></div>
							<div class="text pl-3">
								<h4>Notifications</h4>
								<p>This feature enables you to be notified whenever there is a change in the program
								</p>
							</div>
						</div>
						<div class="col-md-6 services-2 w-100 d-flex">
							<div class="icon d-flex align-items-center justify-content-center"><span
									class="flaticon-emergency-call"></span></div>
							<div class="text pl-3">
								<h4>Marketing</h4>
								<p>It provides a platform to market your product.</p>
							</div>
						</div>
						<div class="col-md-6 services-2 w-100 d-flex">
							<div class="icon d-flex align-items-center justify-content-center"><span
									class="flaticon-veterinarian"></span></div>
							<div class="text pl-3">
								<h4>Veterinary Help</h4>
								<p>Far far away, behind the word mountains, far from the countries.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	

	




	<footer >
		<div class="container">
			
			
			
		</div>
	</footer>




	<!-- loader -->
	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
			<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
			<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
				stroke="#F96D00" /></svg></div>


	<script src="../../../static/js/jquery.min.js"></script>
	<script src="../../../static/js/jquery-migrate-3.0.1.min.js"></script>
	<script src="../../../static/js/popper.min.js"></script>
	<script src=".../../../static/js/bootstrap.min.js"></script>
	<script src="../../../static/js/jquery.easing.1.3.js"></script>
	<script src=".../../../static/js/jquery.waypoints.min.js"></script>
	<script src="../../../static/js/jquery.stellar.min.js"></script>
	<script src=".../../../static/js/jquery.animateNumber.min.js"></script>
	<script src="../../../static/js/bootstrap-datepicker.js"></script>
	<script src="../../../static/js/jquery.timepicker.min.js"></script>
	<script src=".../../../static/js/owl.carousel.min.js"></script>
	<script src="../../../static/js/jquery.magnific-popup.min.js"></script>
	<script src="../../../static/js/scrollax.min.js"></script>
	<script
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
	<script src="../../../static/js/google-map.js"></script>
	<script src=".../../../static/js/main.js"></script>



</body>

</html>

app/user_management/templates/user_management/programs.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap"
    rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="../../../static/css/animate.css">

  <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="../../../static/css/magnific-popup.css">


  <link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
  <link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">

  <link rel="stylesheet" href="../../../static/css/flaticon.css">
  <link rel="stylesheet" href="../../../static/css/style.css">
</head>

<body>

  <div class="wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-6 d-flex align-items-center">
          <p class="mb-0 phone pl-md-2">

            <a href="#"><span class="fa fa-paper-plane mr-1"></span> chickenrearing@.com</a>
          </p>
        </div>
        <!-- <div class="col-md-6 d-flex justify-content-md-end">
          <div class="social-media">
            <p class="mb-0 d-flex">
              <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i
                    class="sr-only">Facebook</i></span></a>
              <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i
                    class="sr-only">Twitter</i></span></a>

            </p>
          </div>
        </div> -->
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('user_management.index') }}"><span
          class="flaticon-pawprint-1 mr-2"></span>Chicken Rearing </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{{ url_for('user_management.index') }}" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="{{ url_for('user_management.get_program')}}" class="nav-link">Managing
              Chicken</a></li>

          <li class="nav-item"> <a href="{{ url_for('products.add_product')}}" class="nav-link">Market Your Product</a>
          </li>
          {% if current_user.is_anonymous %}
          <li class="nav-item"> <a href="{{ url_for('authentication.login')}}" class="nav-link">Login</a></li>
          {% else %}
          <li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"
              class="nav-link">Profile</a></li>
          <li class="nav-item"> <a href="{{ url_for('authentication.logout')}}" class="nav-link">LogOut</a></li>
          {% endif %}
        </ul>

      </div>
    </div>
  </nav>
  <!-- END nav -->



  <div class="container">


    <div class="row">
     

      <div class="col-8">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#subscribe">
          Subscribe all
        </button>
        <div class="card">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col"> Program Name</th>
                <th scope="col">Program Description</th>
                <th scope="col">Handle</th>
              </tr>
            </thead>
            <tbody>
              {% for program in programs %}
              <tr>
                <th scope="row">{{ program.program_id }}</th>
                <td>

                  <a href="{{ url_for('user_management.specific_program', program_id= program.program_id) }}">
                    {{ program.program_name }} </a>
                </td>
                <td>{{ program.program_description }}</td>
                <td>
                  Edit

                </td>

              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div>
      </div>

    </div>

    <!-- Content here -->

  </div>
  

  <!-- Modal -->
  <div class="modal fade" id="subscribe" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="subscribetitle">Subscribe</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <form action="{{ url_for('user_management.subscribe_all') }}" method="POST">
           
            
            <div class="form-group">
              <label for="age">Age in days</label>
              <input type="number" class="form-control" id="age" name="age" 
                placeholder="Enter your chickens' age">
              <small id="agehelp" class="form-text text-muted">In days.</small>
            </div>

            <button type="submit" class="btn btn-primary">Activate</button>
            
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
      </div>
    </div>
  </div>











  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#F96D00" /></svg></div>


  <script src="../../../static/js/jquery.min.js"></script>
  <script src="../../../static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="../../../static/js/popper.min.js"></script>
  <script src=".../../../static/js/bootstrap.min.js"></script>
  <script src="../../../static/js/jquery.easing.1.3.js"></script>
  <script src=".../../../static/js/jquery.waypoints.min.js"></script>
  <script src="../../../static/js/jquery.stellar.min.js"></script>
  <script src=".../../../static/js/jquery.animateNumber.min.js"></script>
  <script src="../../../static/js/bootstrap-datepicker.js"></script>
  <script src="../../../static/js/jquery.timepicker.min.js"></script>
  <script src=".../../../static/js/owl.carousel.min.js"></script>
  <script src="../../../static/js/jquery.magnific-popup.min.js"></script>
  <script src="../../../static/js/scrollax.min.js"></script>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="../../../static/js/google-map.js"></script>
  <script src=".../../../static/js/main.js"></script>



</body>

</html>

app/user_management/templates/user_management/specific_program.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap"
    rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="../../../static/css/animate.css">

  <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="../../../static/css/magnific-popup.css">


  <link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
  <link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">

  <link rel="stylesheet" href="../../../static/css/flaticon.css">
  <link rel="stylesheet" href="../../../static/css/style.css">
</head>

<body>

  <div class="wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-6 d-flex align-items-center">
          <p class="mb-0 phone pl-md-2">
            
            <a href="#"><span class="fa fa-paper-plane mr-1"></span> chickenrearing@.com</a>
          </p>
        </div>
        <!-- <div class="col-md-6 d-flex justify-content-md-end">
          <div class="social-media">
            <p class="mb-0 d-flex">
              <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i
                    class="sr-only">Facebook</i></span></a>
              <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i
                    class="sr-only">Twitter</i></span></a>

            </p>
          </div>
        </div> -->
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('user_management.index') }}"><span
          class="flaticon-pawprint-1 mr-2"></span>Chicken Rearing </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{{ url_for('user_management.index') }}" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="{{ url_for('user_management.get_program')}}" class="nav-link">Managing
              Chicken</a></li>

          <li class="nav-item"> <a href="{{ url_for('products.add_product')}}" class="nav-link">Market Your Product</a>
          </li>
          {% if current_user.is_anonymous %}
          <li class="nav-item"> <a href="{{ url_for('authentication.login')}}" class="nav-link">Login</a></li>
          {% else %}
          <li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"
              class="nav-link">Profile</a></li>
          <li class="nav-item"> <a href="{{ url_for('authentication.logout')}}" class="nav-link">LogOut</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- END nav -->
  <br>
  <br>
  <br>



  <div class="container">
    <div class="row">


      <div class="col-8 mx-auto">
        <div class="card ">
          <br>
          <br>
          <div class=" card-header ">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#subscribe">
              Subscribe
            </button>
            <a type="button" class="btn btn-primary" href="{{ url_for('user_management.get_user_programs',user = current_user.id) }}">
              Your Subscriptions
            </a>


          <h3>Program Name : {{ program.program_name }}</h3>
          <h3>Program Description {{ program.program_description }}</h3>
          </div>

          <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col"> Stage Name</th>
                <th scope="col">Stage Duration</th>
                <th scope="col">Events</th>
              </tr>
            </thead>
            <tbody>
              {% set rowno = 1 %}
              {% for stage,event in result.items() %}
              <tr>
                <th scope="row"> 1 </th>

                <td>{{ stage[0] }}</td>
                <td>{{ stage[1] }} - {{ stage[2] }}</td>
                {% for i in event%}
                {% set rowno = rowno + 1 %}
                <td rowspan="rowno">

                <td>{{ i }}</td>

                </td>
                {% endfor %}


              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div>


      </div>
    </div>

  </div>
  </div>

  </div>


  <!-- Content here -->

  </div>


  <!-- Modal -->
  <div class="modal fade" id="subscribe" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="subscribetitle">Subscribe</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <form action="{{  url_for('user_management.subscribe',program_id=program.program_id ) }}" method="POST">
            
            <div class="form-group">
              <label for="age">Age in days</label>
              <input type="number" class="form-control" id="age" name="age" 
                placeholder="Enter your chickens' age">
              <small id="agehelp" class="form-text text-muted">In days.</small>
            </div>

            <button type="submit" class="btn btn-primary">Activate</button>
            
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
      </div>
    </div>
  </div>










  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#F96D00" /></svg></div>


  <script src="../../../static/js/jquery.min.js"></script>
  <script src="../../../static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="../../../static/js/popper.min.js"></script>
  <script src=".../../../static/js/bootstrap.min.js"></script>
  <script src="../../../static/js/jquery.easing.1.3.js"></script>
  <script src=".../../../static/js/jquery.waypoints.min.js"></script>
  <script src="../../../static/js/jquery.stellar.min.js"></script>
  <script src=".../../../static/js/jquery.animateNumber.min.js"></script>
  <script src="../../../static/js/bootstrap-datepicker.js"></script>
  <script src="../../../static/js/jquery.timepicker.min.js"></script>
  <script src=".../../../static/js/owl.carousel.min.js"></script>
  <script src="../../../static/js/jquery.magnific-popup.min.js"></script>
  <script src="../../../static/js/scrollax.min.js"></script>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="../../../static/js/google-map.js"></script>
  <script src=".../../../static/js/main.js"></script>



</body>

</html>