app/products/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.fields import IntegerField, SelectField, SubmitField, TextAreaField, TextField

from wtforms.validators import DataRequired, Length
from wtforms.fields.core import StringField
from flask  import request

# class ProductForm(FlaskForm):
#     product_type = SelectField('Product Type', choices=[('Eggs','Eggs'),('Chicks','Chicks'),('Broilers','Broilers'),('Layers','Layers')])
#     quantity = IntegerField('Quantity')
#     product_description = TextAreaField('About Me',validators=[Length(min=0,max=140)])
#     image_path = FileField('Image',validators=[FileRequired(),FileAllowed(['jpg','png'],'An Image is Required')])
#     submit = SubmitField('Post')
    
class EmptyForm():
    submit = SubmitField('Submit')
    
    
class SearchForm(FlaskForm):
     q = StringField('Search', validators=[DataRequired()])
     
     
     def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

app/products/__init__.py
from flask import Blueprint

product_blueprint = Blueprint('products',__name__,template_folder="templates")
from app.products import forms,routes

app/products/routes.py
from flask import flash, send_from_directory, url_for,request,current_app,request,g
from fileinput import filename
from flask.templating import render_template
from app.products import product_blueprint
from flask_login import current_user, login_required
import os
from os import path
from app import db
from app.models import Comment, Product

from werkzeug.utils import redirect, secure_filename

import app
import imghdr
import datetime
from app.products.forms import SearchForm


   




def validate_image(stream):
    header = stream.read(512)
    stream.seek(0)
    format = imghdr.what(None,header)
    if not format:
        return None
    return '.' + (format if format != 'jpeg' else 'jpg')

# def allowed_file(filename):
    
#     return '.' in filename and \
#         filename.rsplit('.,1')[1].lower() in current_app.Config['ALLOWED_EXTENSIONS']

           
@product_blueprint.route('/add_product', methods=['POST','GET'])
@login_required

def add_product():
           
    return render_template('products/create_product.html') 
  
@product_blueprint.route('/addd_product', methods=['POST','GET'])
@login_required
def addd_product():
    if request.method == "POST":
        request_data = request.form
        product_type = request_data.get("product_type")
        quantity = request_data.get("quantity")
        product_description =request_data.get("product_description")
        
        image = request.files.get("image")
        filename = secure_filename(image.filename)
        if filename !='':
            file_extension = os.path.splitext(filename)[1]
            if file_extension not in current_app.config['ALLOWED_EXTENSIONS'] or \
                file_extension != validate_image(image.stream):
                    flash("no image file")
            image.save(os.path.join(current_app.config['UPLOAD_FOLDER'],filename))
            image_path = image.filename
            
            print(image_path)

    
            product = Product(product_type=product_type,quantity=quantity,product_description=product_description,image_path=image_path,user_id = current_user.id)
            print(product)
           
            db.session.add(product)
            db.session.commit()
            flash('Product Added Successfully!')
        else:
           flash('Error in adding your product!') 
        
        
    
    
    return redirect(url_for('products.view_product'))
   # return render_template('products/products.html')
        
@product_blueprint.route('/view_product', methods=['GET','POST'])
@login_required
def view_product():
    # return 'View product Page'
    
    page = request.args.get('page',1,type=int)
    product_result =Product.query.order_by(Product.timestamp.desc()).paginate(page,current_app.config['POSTS_PER_PAGE'],False)
    print(product_result)
    next_url = url_for('view_product',page=product_result.next_num)\
         if product_result.has_next else None
        
    prev_url = url_for('view_product', page=product_result.prev_num)\
         if product_result.has_prev else None  
     
    return render_template('products/products.html',product_result= product_result.items, next_url=next_url, prev_url=prev_url)
    

    # return render_template('products/products.html',products=productswithImage.items)
    
    

#getting image from folder
@product_blueprint.route('/download_image/<image_path>')
def download_image(image_path):
    # 
    # return send_from_directory(os.path.join(current_app.config['UPLOAD_FOLDER']),image_path,as_attachment=True)
    return redirect(url_for('static',filename='uploads/' +image_path), code=301)

@product_blueprint.route('/search')
@login_required
def search():
    
    if not g.search_form.validate():
        return redirect(url_for('product_blueprint.view_product'))
    page = request.args.get('page', 1, type=int)
    posts, total = Product.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('product_blueprint.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('product_blueprint.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title='Search', posts=posts, next_url=next_url, prev_url=prev_url)
                       
 

 ######WORK ON COMMENTING   
@product_blueprint.route('/comment_product/<product_id>/<comment_id>',methods=['GET','POST'])
@login_required  
   
def comment_product(product_id,comment_id):
    product = Product.query.get_or_404(product_id)
    comment_id = Comment.query.get_or_404(id)
    comments = Comment.query.order_by(Comment.timestamp.desc().all)
    if request.method == 'POST':
        req = request.form
        text = req.get('comment')
        
        if comment_id:
            comment =Comment(text=comment,author=current_user.id,parent_id=comment_id,product_id=product_id)
            # comment.save()
            db.session.add(comment)
            db.session.commit()
        else:
            comment = Comment(text = comment,author= current_user.id, parent_id= 0, Product=product_id)
            db.session.add(comment)
            db.session.commit()
        
    
            
    
    # result = Comment.query.order_by(Comment.path)
    return render_template('Products/products.html',comments=comments,product=product)

@product_blueprint.route('/comment/<product_id>/<comment_id>',methods=['GET','POST'])
def comment(product_id,comment_id=0):
    
    return render_template('products/comment.html',product_id=product_id,comment_id=comment_id)
        

app/products/templates/products/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
 
  
    <form action="{{ url_for('products.comment_product',product_id=product_id,comment_id=comment_id) }} " method="POST">
        <div class="form-group">
          <label for="comment">Comment</label>
          <input type="text" class="form-control" id="comment" placeholder="add your comment here">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Post</button>
      </form>
    
</body>
</html>

app/products/templates/products/products.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap"
    rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="../../../static/css/animate.css">

  <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="../../../static/css/magnific-popup.css">


  <link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
  <link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">

  <link rel="stylesheet" href="../../../static/css/flaticon.css">
  <link rel="stylesheet" href="../../../static/css/style.css">
</head>

<body>

  <div class="wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-6 d-flex align-items-center">
          <p class="mb-0 phone pl-md-2">
            <a href="#" class="mr-2"><span class="fa fa-phone mr-1"></span> +254711264880</a>
            <a href="#"><span class="fa fa-paper-plane mr-1"></span> chickenrearing@.com</a>
          </p>
        </div>
        <div class="col-md-6 d-flex justify-content-md-end">
          <div class="social-media">
            <p class="mb-0 d-flex">
              <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i
                    class="sr-only">Facebook</i></span></a>
              <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i
                    class="sr-only">Twitter</i></span></a>

            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('user_management.index') }}"><span
          class="flaticon-pawprint-1 mr-2"></span>Chicken Rearing </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item active"><a href="{{ url_for('user_management.index') }}" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="{{ url_for('user_management.get_program')}}" class="nav-link">Managing
              Chicken</a></li>

          <li class="nav-item"> <a href="{{ url_for('products.view_product')}}" class="nav-link">Market Your Product</a>
          </li>
          {% if current_user.is_anonymous %}
          <li class="nav-item"> <a href="{{ url_for('authentication.login')}}" class="nav-link">Login</a></li>
          {% else %}
          <li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"
              class="nav-link">Profile</a></li>
          <li class="nav-item"> <a href="{{ url_for('authentication.logout')}}" class="nav-link">LogOut</a></li>
          {% endif %}

        </ul>
        {% if g.search_form %}
        <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
          <div class="form-group">
            {{ g.search_form.q(size=20, class='form-control',
                            placeholder=g.search_form.q.label.text) }}
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>
  <!-- END nav -->


  <!-- display products -->
  <!-- <section class="ftco-section bg-light ftco-no-pt ftco-intro"> -->

  <main role="main" class="container">

    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
      <a href="{{ url_for('products.add_product')}}" class="btn btn-primary">Post Your Product</a>
      <div class="lh-100">
        <h6 class="mb-0 text-white lh-100"></h6>
        <small></small>
      </div>
    </div>

    {% for product in product_result %}
    <div class="row mx-auto">

      <div class=" col-8">



        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">



              <p>{{ product.product_type }}</p>
              <p>{{ product.product_quantity }}</p>
              <p>{{ product.product_description }}</p>



              <img class="card-img-bottom"
                src="{{ url_for('products.download_image', image_path= product.image_path) }}" alt="Card image cap">

          </div>
          <div id="disqus_thread"></div>
          <script>

            /**
            *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
            *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
            /*
            var disqus_config = function () {
            this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            };
            */
            (function () { // DON'T EDIT BELOW THIS LINE
              var d = document, s = d.createElement('script');
              s.src = 'https://kukuapp.disqus.com/embed.js';
              s.setAttribute('data-timestamp', +new Date());
              (d.head || d.body).appendChild(s);
            })();
          </script>
        


          <a href="{{ url_for('products.comment',product_id = product.product_id,comment_id = 0) }}"> <img
              src="../../../static/icons/chat-left.svg" alt="" width="40" height="40" title="Comment"></a>
          <img src="../../../static/icons/eye.svg" alt="" width="40" height="40" title="Views">




        </div>
        <br>
      </div>




    </div>

    </div>
    <br>
    <br>

    {% endfor %}

    </div>

    </div>
    </div>
  </main>
  <!-- display product -->










  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#F96D00" /></svg></div>


  <script src="../../../static/js/jquery.min.js"></script>
  <script src="../../../static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="../../../static/js/popper.min.js"></script>
  <script src=".../../../static/js/bootstrap.min.js"></script>
  <script src="../../../static/js/jquery.easing.1.3.js"></script>
  <script src=".../../../static/js/jquery.waypoints.min.js"></script>
  <script src="../../../static/js/jquery.stellar.min.js"></script>
  <script src=".../../../static/js/jquery.animateNumber.min.js"></script>
  <script src="../../../static/js/bootstrap-datepicker.js"></script>
  <script src="../../../static/js/jquery.timepicker.min.js"></script>
  <script src=".../../../static/js/owl.carousel.min.js"></script>
  <script src="../../../static/js/jquery.magnific-popup.min.js"></script>
  <script src="../../../static/js/scrollax.min.js"></script>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="../../../static/js/google-map.js"></script>
  <script src=".../../../static/js/main.js"></script>



</body>

</html>

app/products/templates/products/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 
    <link rel="stylesheet" href="../../../static/css/animate.css">
    
    <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
    <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="../../../static/css/magnific-popup.css">


    <link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">

    <link rel="stylesheet" href="../../../static/css/flaticon.css">
    <link rel="stylesheet" href="../../../static/css/style.css">
  </head>
  <body>

    <div class="wrap">
			<div class="container">
				<div class="row">
					<div class="col-md-6 d-flex align-items-center">
						<p class="mb-0 phone pl-md-2">
							<a href="#" class="mr-2"><span class="fa fa-phone mr-1"></span> +254711264880</a> 
							<a href="#"><span class="fa fa-paper-plane mr-1"></span> chickenrearing@.com</a>
						</p>
					</div>
					<div class="col-md-6 d-flex justify-content-md-end">
						<div class="social-media">
			    		<p class="mb-0 d-flex">
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
			    			<a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
			    			
			    		</p>
		        </div>
					</div>
				</div>
			</div>
		</div>
		<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	    	<a class="navbar-brand" href="{{ url_for('user_management.index') }}"><span class="flaticon-pawprint-1 mr-2"></span>Chicken Rearing </a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="fa fa-bars"></span> Menu
	      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
            
            <li class="nav-item active"><a href="{{ url_for('user_management.index') }}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="{{ url_for('user_management.get_program')}}" class="nav-link">Managing Chicken</a></li>
            
            <li class="nav-item"> <a href="{{ url_for('products.view_product')}}"class="nav-link">Market Your Product</a></li>
            {% if current_user.is_anonymous %}
            <li class="nav-item"> <a href="{{ url_for('authentication.login')}}"class="nav-link">Login</a></li>
            {% else %}
            <li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"class="nav-link">Profile</a></li>
            <li class="nav-item"> <a href="{{ url_for('authentication.logout')}}"class="nav-link">LogOut</a></li>
            {% endif %}

          </ul>
          {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get"
                        action="{{ url_for('main.search') }}">
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control',
                            placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    <a href="{{ url_for('products.addd_product')}}" class="btn btn-primary">Post Your Product</a>
    

    <section class="ftco-section bg-light ftco-no-pt ftco-intro">
    	<div class="container">
    		<div class="row mx-auto">
          
          {% for product in products %}
          <div class=" col-8">

          
                
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">
                
                

               <p>{{ product.product_type }}</p>
               
               <p>{{ product.product_quantity }}</p>
               
               <p>{{ product.product_description }}</p>
               
               <p>{{ product.image_path }}</p>
               
               <img class="card-img-bottom" src="{{ url_for( 'products.download_image', image_path= product.image_path  ) }}" alt="Card image cap">
              
               </div>
               <br>
               

          <div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://chickenapp.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
          
          
               
             
</div>
          
</div>
<br>
<br>

          
          {% endfor %}

        </div>

    		</div>    
    	</div>
    </section>

    

    
   
   
    <footer class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-lg-3 mb-4 mb-md-0">
						<h2 class="footer-heading">Petsitting</h2>
						<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
						<ul class="ftco-footer-social p-0">
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><span class="fa fa-twitter"></span></a></li>
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><span class="fa fa-facebook"></span></a></li>
              <li class="ftco-animate"><a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><span class="fa fa-instagram"></span></a></li>
            </ul>
					</div>
					<div class="col-md-6 col-lg-3 mb-4 mb-md-0">
						<h2 class="footer-heading">Latest News</h2>
						<div class="block-21 mb-4 d-flex">
              <a class="img mr-4 rounded" style="background-image: url(../../../static/images/image_1.jpg);"></a>
              <div class="text">
                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                <div class="meta">
                  <div><a href="#"><span class="icon-calendar"></span> April 7, 2020</a></div>
                  <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                  <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                </div>
              </div>
            </div>
            <div class="block-21 mb-4 d-flex">
              <a class="img mr-4 rounded" style="background-image: url(../../../static/images/image_2.jpg);"></a>
              <div class="text">
                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                <div class="meta">
                  <div><a href="#"><span class="icon-calendar"></span> April 7, 2020</a></div>
                  <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                  <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                </div>
              </div>
            </div>
					</div>
					<div class="col-md-6 col-lg-3 pl-lg-5 mb-4 mb-md-0">
						<h2 class="footer-heading">Quick Links</h2>
						<ul class="list-unstyled">
              unstyled">
              <li class="nav-item active"><a href="{{ url_for('user_management.index') }}" class="nav-link">Home</a></li>
              <li class="nav-item"><a href="{{ url_for('user_management.get_program')}}" class="nav-link">Managing Chicken</a></li>
              
              <li class="nav-item"> <a href="{{ url_for('products.view_product')}}"class="nav-link">Market Your Product</a></li>
              {% if current_user.is_anonymous %}
              <li class="nav-item"> <a href="{{ url_for('authentication.login')}}"class="nav-link">Login</a></li>
              {% else %}
              <li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"class="nav-link">Profile</a></li>
              <li class="nav-item"> <a href="{{ url_for('authentication.logout')}}"class="nav-link">LogOut</a></li>
              {% endif %}
         
            </ul>
					</div>
					<div class="col-md-6 col-lg-3 mb-4 mb-md-0">
						<h2 class="footer-heading">Have a Questions?</h2>
						<div class="block-23 mb-3">
              <ul>
                <li><span class="icon fa fa-map"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                <li><a href="#"><span class="icon fa fa-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                <li><a href="#"><span class="icon fa fa-paper-plane"></span><span class="text">info@yourdomain.com</span></a></li>
              </ul>
            </div>
					</div>
				</div>
				<div class="row mt-5">
          <div class="col-md-12 text-center">

            <p class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
			</div>
		</footer>

    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="../../../static/js/jquery.min.js"></script>
  <script src="../../../static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="../../../static/js/popper.min.js"></script>
  <script src=".../../../static/js/bootstrap.min.js"></script>
  <script src="../../../static/js/jquery.easing.1.3.js"></script>
  <script src=".../../../static/js/jquery.waypoints.min.js"></script>
  <script src="../../../static/js/jquery.stellar.min.js"></script>
  <script src=".../../../static/js/jquery.animateNumber.min.js"></script>
  <script src="../../../static/js/bootstrap-datepicker.js"></script>
  <script src="../../../static/js/jquery.timepicker.min.js"></script>
  <script src=".../../../static/js/owl.carousel.min.js"></script>
  <script src="../../../static/js/jquery.magnific-popup.min.js"></script>
  <script src="../../../static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="../../../static/js/google-map.js"></script>
  <script src=".../../../static/js/main.js"></script>


    
  </body>
</html>