app/AdminProgramManagement/__init__.py
from flask import Blueprint

admin_program_management_blueprint = Blueprint('AdminProgramManagement', __name__,template_folder="templates")


from app.AdminProgramManagement import routes,reports

app/AdminProgramManagement/routes.py
from app import db

from flask import url_for,redirect,request
from app.models import Event, Program, Stage
# from app.AdminProgramManagement.forms import ProgramForm, StageForm
from app.AdminProgramManagement import admin_program_management_blueprint
from flask.json import jsonify
from flask.templating import render_template
from dns.resolver import query
from flask.helpers import flash, make_response
import json
from wtforms.csrf import session
from wtforms import form
from sqlalchemy  import update
from app.decorators import admin_required
from flask_login import current_user,login_required
from itertools import groupby
from operator import itemgetter


@admin_program_management_blueprint.route('/index',methods=['POST','GET'])
@login_required
@admin_required
def index():
    
    return ('This is index page')
    # return redirect(url_for('AdminProgramManagement.fetch_programs'))

@admin_program_management_blueprint.route('/add_program', methods=['POST','GET'])
@login_required
@admin_required
def add_program():
    
    if request.method == 'POST':
        request_result = request.form
        program_name = request_result.get('program_name')
        program_description = request_result.get('program_description')
        
        program = Program(program_name=program_name,program_description=program_description)
        db.session.add(program)
        db.session.commit()
        flash('Program Added!!')
    
    
    return redirect (url_for('AdminProgramManagement.fetch_programs'))
                     
                     
@admin_program_management_blueprint.route('/fetch_programs', methods=['POST','GET'])  
@login_required
@admin_required                  
def fetch_programs():
    programs = Program.query.all()
    
   
        
    return render_template('AdminProgramManagement/program.html',programs=programs)


@admin_program_management_blueprint.route('/program_update/<program_id>' ,methods = ['POST','GET'])
@login_required
@admin_required
def program_update(program_id):
    
    return render_template('AdminProgramManagement/update_program.html',program_id=program_id)


@admin_program_management_blueprint.route('/update_program/<program_id>' ,methods = ['POST','GET'])
@login_required
@admin_required
def update_program(program_id):
    
    program = Program.query.filter(Program.program_id == program_id).first()
    
    if request.method == 'POST':
        req = request.form
        program.program_name = req.get('program_name')
        program.program_description = req.get('program_description')
        
        # stmt = Program.update().where(Program.c.program_id == program_id).\
        #     values(program_name=program_name_update,program_description=program_description_update)
            
        db.session.commit()
        
        
    programs = Program.query.all()
    
   
        
    return render_template('AdminProgramManagement/program.html',programs=programs)
        
    # return redirect('AdminProgramManagement.fetch_programs')
       
        
        
@admin_program_management_blueprint.route('/delete_program/<program_id>' ,methods = ['POST','GET'])
@login_required
@admin_required
def delete_program(program_id):
    
    result = db.session.query(Program).get(program_id)
    db.session.delete(result)
    db.session.commit()
    
    return redirect(url_for('AdminProgramManagement.fetch_programs'))


# @admin_program_management_blueprint.route('/add_stage/<program_id>', methods = ['POST','GET'])
# @login_required
# @admin_required
# def add_stage(program_id):
#     program_id=program_id
    
#     return render_template('AdminProgramManagement/add_stage.html',program_id=program_id)
    
    


@admin_program_management_blueprint.route('/add_stage/<program_id>' ,methods = ['POST','GET'])
@login_required
@admin_required
def add_stage(program_id):

    if request.method == 'POST' and program_id is not None:
            
            stage_name = request.form['stage_name']
            start = request.form['start']
            end = request.form['end']
            event_list = request.form.getlist("TableData")  ###NOT WORKING
            # event_list = json.loads(events)
            
            print(stage_name)
            print(event_list)
           
            stage = Stage(stage_name=stage_name,start=start,end=end,program_id = program_id)
            for event_input in range(len(event_list)):
                stage.event.append(event_input)
            
            db.session.add(stage)
            db.session.commit()
            print('Submission Sucessful')
            
            res = make_response(jsonify(event_list,stage_name,start,end), 200)

            # return res
            return redirect (url_for('AdminProgramManagement.view_program', program_id = program_id))

       
            
    else:
        return render_template('AdminProgramManagement/add_stage.html',program_id=program_id)
    
    return redirect (url_for('AdminProgramManagement.view_program', program_id = program_id))
    




@admin_program_management_blueprint.route('/view_program/<program_id>', methods=['POST','GET'])  
@login_required
@admin_required
def view_program(program_id):
    program = Program.query.filter(Program.program_id == program_id).first()
    

    results = db.session.query(Stage.stage_name,Stage.start,Stage.end,Event.event_description).join(Event).join(Program).\
        filter(Program.program_id == program_id).all()

     
    print(results) 
    print(program)
    result_dict = {}
    result =convert(results,result_dict)
    # list_result = [(k,v) for k,v in result.items()]
   
    return render_template('AdminProgramManagement/view_program.html',program_id = program_id,program=program,result=result)

def convert(tupl, dic):
    y=()
    x = []
    for name,start,end,event in tupl:
        x.append(name)
        x.append(start)
        x.append(end)
        s=x[-3:]
        y=tuple(s)
        dic.setdefault(y,[]).append(event)
        
        
    return dic

@admin_program_management_blueprint.route('/delete_stage/<stage_id>', methods=['POST','GET'])
@login_required
@admin_required
def delete_stage(stage_id):
    
    result = db.session.query(Stage).get(stage_id)
    db.session.delete(result)
    db.session.commit()
    
    return redirect(url_for('AdminProgramManagement.view_program'))
        

@admin_program_management_blueprint.route('/update_stage/<stage_id>')   
@login_required
@admin_required     
def update_stage(stage_id):
     stage = Stage.query.filter(Stage.stage_id == stage_id).first()
     events = db.session.query(Event).join(Stage).filter(Stage.stage_id == stage_id).all()
    
     if request.method == 'POST':
         
         req = request.form
         stage.stage_name = req.get('stage_name')
         stage.start = req.get('start')
         stage.end = req.get('end')
         
         event_list=req.getlist('event_list')
         
         
         
         db.session.commit()
        
     return redirect(url_for('AdminProgramManagement.view_program'))
    
        
    
        
    

         

app/AdminProgramManagement/templates/AdminProgramManagement/add_stage.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap"
    rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="../../../static/css/animate.css">

  <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="../../../static/css/magnific-popup.css">


  <link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
  <link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">

  <link rel="stylesheet" href="../../../static/css/flaticon.css">
  <link rel="stylesheet" href="../../../static/css/style.css">






</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('user_management.index') }}"><span
          class="flaticon-pawprint-1 mr-2"></span>Chicken Rearing </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span> Menu
      </button>
      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{{ url_for('AdminProgramManagement.index') }}"
              class="nav-link">Dashboard</a>
          </li>
          <li class="nav-item"><a href="{{ url_for('AdminProgramManagement.fetch_programs')}}" class="nav-link">Manage
              Chicken</a>
          </li>
          <li class="nav-item"><a href="{{ url_for('products.view_product')}}" class="nav-link">Products</a></li>

          {% if current_user.is_anonymous %}
          <li class="nav-item"> <a href="{{ url_for('authentication.login')}}" class="nav-link">Login</a></li>
          {% else %}
          <li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"
              class="nav-link">Profile</a></li>
          <li class="nav-item"> <a href="{{ url_for('authentication.logout')}}" class="nav-link">LogOut</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <br>
  <br>

  <div class="row mx-auto  ">
    <div class="col-sm-8 mx-auto ">
      <div class="card  mx-auto">
        <div class="card-body">
          <form action="{{ url_for('AdminProgramManagement.add_stage',program_id = program_id ) }} " method="POST">

            <div class="form-group">
              <label for="stage_name">Stage Name</label>
              <input type="text" class="form-control" id="stage_name" name="stage_name">

            </div>
            <div class="form-group">
              <label for="start">Start</label>
              <input type="number" class="form-control" id="start" name="start">
            </div>

            <div class="form-group">
              <label for="end">End</label>
              <input type="number" class="form-control" id="end" name="end">
            </div>

            <div class="form-inline">
              <div class="form-group mb-2">
                <label for="event">Event</label>
                <input type="text" class="form-control" id="event" name="event">
              </div>
              <button type="button" class="btn btn-primary" name="add_event" id="addBtn">Add Another Event</button>
            </div>

            <div class="form-group">
              <table class="table" id="event_list" name="event_list">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Events</th>

                  </tr>
                </thead>
                <tbody id="tbody">



                </tbody>
              </table>
            </div>


            <button type="submit" id="submit" class="btn btn-primary btn-lg "> Submit</button>

          </form>

        </div>

      </div>
    </div>

  </div>



</body>
<script>
  $(document).ready(function () {

    // Denotes total number of rows 
    var rowIdx = 0;

    // jQuery button click event to add a row 
    $('#addBtn').on('click', function () {
      var event = document.getElementById('event').value;
      // Adding a row inside the tbody. 
      $('#tbody').append(`<tr id="R${++rowIdx}"> 
         <td class="row-index text-center"> 
         <p> ${rowIdx}</p> 
         </td> 
         <td class=" text-center"> 
         <p> ${event} </p> 
         </td>
          <td class="text-center"> 
            <button class="btn btn-danger remove"
              type="button">Remove</button> 
            </td> 
          </tr>`);
    });

    // jQuery button click event to remove a row. 
    $('#tbody').on('click', '.remove', function () {

      // Getting all the rows next to the row 
      // containing the clicked button 
      var child = $(this).closest('tr').nextAll();

      // Iterating across all the rows  
      // obtained to change the index 
      child.each(function () {

        // Getting <tr> id. 
        var id = $(this).attr('id');

        // Getting the <p> inside the .row-index class. 
        var idx = $(this).children('.row-index').children('p');

        // Gets the row number from <tr> id. 
        var dig = parseInt(id.substring(1));

        // Modifying row index. 
        idx.html(`Row ${dig - 1}`);

        // Modifying row id. 
        $(this).attr('id', `R${dig - 1}`);
      });

      // Removing the current row. 
      $(this).closest('tr').remove();

      // Decreasing total number of rows by 1. 
      rowIdx--;
    });
  });



  $(document).ready(function () {

    $(function () {
      $('#submit').click(function () {

        var TableData = [];
        $('#event_list tr').each(function (row, tr) {
          TableData[row] = $(tr).find('td:eq(1)').text()

        });
        TableData.shift();

        var stage_name = $('#stage_name').val();
        var start = $('#start').val();
        var end = $('#end').val();


        alert(TableData);

        var myTableData = {
          stage_name: stage_name,
          start: start,
          end: end,
          TableData: [{
            TablEData:TableData}
        ]
        }
        alert (myTableData)
        // data: $(form,TableData).serializeArray()

        $.ajax({
          url: '/add_Stage/<program_id>',
          contentType: 'application/json; charset=utf-8',
          dataType:JSON,
          data: JSON.stringify(myTableData),
          type: 'POST',
          success: function (response) {
            console.log(response);
          },
          error: function (error) {
            console.log(error);
          }
        });
      });
    });

  })




// function submit(){
//   var stage_name = document.getElementById("stage_name");
//   var start = document.getElementById("start");
//   var end = document.getElementById("end");

//   var myTableArray =[];
//   $("table #event_list tr").each(function() {
//       var arrayOfThisRow = [];
//       var tableData = $(this).find('td');
//       if (tableData.length > 0) {
//           tableData.each(function() { arrayOfThisRow.push($(this).text()); });
//           myTableArray.push(arrayOfThisRow);
//       }
//   });

// alert(myTableArray);


//   var entry = {
//     stage_name: stage_name.value,
//     start: start.value,
//     end: end.value,
//     event_list: myTableArray
// };
// console.log(entry);

// fetch(`${window.origin}/addd_stage`, {
//       method: "POST",
//       credentials: "include",
//       body: JSON.stringify(entry),
//       cache: "no-cache",
//       headers: new Headers({
//         "content-type": "application/json"
//       })
//     })
//     .then(function (response) {
//         if (response.status !== 200) {
//           console.log(`Looks like there was a problem. Status code: ${response.status}`);
//           return;
//         }
//         response.json().then(function (data) {
//           console.log(data);
//         });
//       })
//       .catch(function (error) {
//         console.log("Fetch error: " + error);
//       });
// }



</script>

</html>

app/AdminProgramManagement/templates/AdminProgramManagement/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> Admin Dashboard </h1>
</body>
</html>

app/AdminProgramManagement/templates/AdminProgramManagement/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> Admin Dashboard </h1>
</body>
</html>

app/AdminProgramManagement/templates/AdminProgramManagement/program.html
<!DOCTYPE html>
<html lang="en">
    <head>
    
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        
        <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     
        <link rel="stylesheet" href="../../../static/css/animate.css">
        
        <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
        <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
        <link rel="stylesheet" href="../../../static/css/magnific-popup.css">
    
    
        <link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
        <link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">
    
        <link rel="stylesheet" href="../../../static/css/flaticon.css">
        <link rel="stylesheet" href="../../../static/css/style.css">
      </head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 d-flex align-items-center">
                <p class="mb-0 phone pl-md-2">
                    <a href="#" class="mr-2"><span class="fa fa-phone mr-1"></span> +254711264880</a> 
                    <a href="#"><span class="fa fa-paper-plane mr-1"></span> chickenrearing@.com</a>
                </p>
            </div>
            <div class="col-md-6 d-flex justify-content-md-end">
                <div class="social-media">
                <p class="mb-0 d-flex">
                    <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
                    <a href="#" class="d-flex align-items-center justify-content-center"><span class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
                    
                </p>
        </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
<div class="container">
    <a class="navbar-brand" href="{{ url_for('user_management.index') }}"><span class="flaticon-pawprint-1 mr-2"></span>Chicken Rearing </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="fa fa-bars"></span> Menu
  </button>
  <div class="collapse navbar-collapse" id="ftco-nav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active"><a href="{{ url_for('AdminProgramManagement.index') }}" class="nav-link">Dashboard</a>
      </li>
      <li class="nav-item"><a href="{{ url_for('AdminProgramManagement.fetch_programs')}}" class="nav-link">Manage Chicken</a>
      </li>
      <li class="nav-item"><a href="{{ url_for('products.view_product')}}" class="nav-link">Products</a></li>

      {% if current_user.is_anonymous %}
      <li class="nav-item"> <a href="{{ url_for('authentication.login')}}" class="nav-link">Login</a></li>
      {% else %}
      <li class="nav-item"> <a href="{{ url_for('user.user', username=current_username) }}"
          class="nav-link">Profile</a></li>
      <li class="nav-item"> <a href="{{ url_for('authentication.logout')}}" class="nav-link">LogOut</a></li>
      {% endif %}
    </ul>
  </div>
</div>
</nav>


 
    

    <div class="container">
      <div class="row">

        
        <div class="col-8">
          <div class="card">
        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col"> Program Name</th>
                <th scope="col">Program Description</th>
                <th scope="col">Handle</th>
              </tr>
            </thead>
            <tbody>
              {% for program in programs %}
              <tr>
                <th scope="row">{{ program.program_id }}</th>
                <td>
                 
                  <a href="{{ url_for('AdminProgramManagement.view_program', program_id = program.program_id)}} "> {{ program.program_name }}</a>
              
                </td>
                <td>{{ program.program_description }}</td> 
                <td><a type="button" class="btn btn-secondary" href="{{ url_for('AdminProgramManagement.delete_program', program_id = program.program_id) }}" >Delete</a>
                  
                  <a href="{{ url_for('AdminProgramManagement.program_update', program_id = program.program_id)}}" type="button" class="btn btn-primary btn-lg"  >
                    Edit
                  </a>
                </td>
                 
              </tr>
              {% endfor %}
             
            </tbody>
          </table>
        </div>
      </div>
        <div class="col-4 text-right">
          <br>
          <br>
          

          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
            Add a Program 
          </button>

         </div>
      </div>
    
        <!-- Content here -->
    
    </div>
   
  
   
      <!-- Button trigger modal -->

  
  <!-- Add Program Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Add a Program</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           
                <form action="{{ url_for('AdminProgramManagement.add_program') }}" method="POST">

                <div class="form-group">
                    <label for="program_name">Program Name</label>
                    <input type="text" class="form-control" id="program_name" name="program_name">
                  </div>

                <div class="form-group">
                <label for="program_description">Program Description</label>
                    <input type="text" class="form-control" id="program_description" name="program_description">
                  </div>

                  <div class="modal-footer"></div>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <button type="submit" class="btn btn-primary">Save changes</button>
                </div>

                </form>
          
        </div>
        
          
        
      </div>
    </div>
  </div>



</body>
</html>

app/AdminProgramManagement/templates/AdminProgramManagement/update_program.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  
  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600,700,800&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="../../../static/css/animate.css">
  
  <link rel="stylesheet" href="../../../static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="../../../static/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="../../../static/css/magnific-popup.css">


  <link rel="stylesheet" href="../../../static/css/bootstrap-datepicker.css">
  <link rel="stylesheet" href=".../../../static/css/jquery.timepicker.css">

  <link rel="stylesheet" href="../../../static/css/flaticon.css">
  <link rel="stylesheet" href="../../../static/css/style.css">

    




</head>
<body>
  <div class="row  center">
    <div class="col-sm-8 ">
  <div class="card">
   <strong>  <h3>Edit Program</h3> </strong>
    <div class="card-body">
   
      <form action="{{ url_for('AdminProgramManagement.update_program', program_id = program_id)}}" method="POST">

        <div class="form-group">
            <label for="program_name">Program Name</label>
            <input type="text" class="form-control" id="program_name" name="program_name">
          </div>

        <div class="form-group">
        <label for="program_description">Program Description</label>
            <input type="text" class="form-control" id="program_description" name="program_description">
          </div>

          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
       

      
        
      </form>

    </div>

  </div>
  </div>

  </div>
      


</body>

</html>

</html>